---

- name: Restart UFW
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
  when: pve_configure_firewall

- name: Enable Port 8006 via ufw
  community.general.ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
  loop: "{{ pve_firewall_rules }}"
  when: pve_configure_firewall

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Proxmox VE
  ansible.builtin.include_tasks: install.yml

- name: Restart UFW
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
  when: pve_configure_firewall

- name: Configure Network
  ansible.builtin.include_tasks: network.yml
  when: pve_configure_network

- name: Configure NGINX for Proxmox VE
  ansible.builtin.include_tasks: nginx.yml
  when: pve_configure_nginx
